---
- name: Install etcd
  hosts: all
  become: true
  remote_user: rocky
  tasks:
    - name: install etcd
      shell: |
        sudo mkdir -p /etc/etcd/pki
        sudo dnf install wget tar -y
        wget https://github.com/etcd-io/etcd/releases/download/v3.5.13/etcd-v3.5.13-linux-amd64.tar.gz
        tar zxf etcd-v3.5.13-linux-amd64.tar.gz
        sudo cp etcd-v3.5.13-linux-amd64/etcd* /usr/local/bin/
        sudo cp etcd-v3.5.13-linux-amd64/etcd* /usr/bin/
        sudo rm -rf etcd*
    - name: copy ca.pem
      copy:
        src: ca.pem
        dest: /etc/etcd/pki/ca.pem
    - name: copy etcd.pem
      copy:
        src: etcd.pem
        dest: /etc/etcd/pki/etcd.pem
    - name: copy etcd-key.pem
      copy:
        src: etcd-key.pem
        dest: /etc/etcd/pki/etcd-key.pem
    - name: copy etcd.service
      copy:
        src: "etcd-0{{ index }}.service"
        dest: /etc/systemd/system/etcd.service
    - name: start and enable etcd
      service:
        name: etcd
        state: started
        enabled: yes
