---
- name: Install k8s
  hosts: all
  become: true
  remote_user: rocky
  gather_facts: false
  tasks:
    - name: disable SELinux
      ansible.posix.selinux:
        state: disabled
    - name: swapoff 1
      shell: |
        swapoff -a
    - name: swapoff 2
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Load module 'br_netfilter'
      modprobe:
        name: br_netfilter
        state: present
    - name: Copy sys conf
      copy:
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf
      register: sysctl_config
    - name: Reload parameters sysctl
      shell: sysctl -p --system
      when: sysctl_config.changed
    - name: Install containerd
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        dnf makecache
        dnf install -y containerd.io
        mv /etc/containerd/config.toml /etc/containerd/config.toml.orig
        containerd config default > /etc/containerd/config.toml
        sed -i "s|SystemdCgroup = false|SystemdCgroup = true|g" /etc/containerd/config.toml
        systemctl enable --now containerd.service
        systemctl status containerd.service --no-pager
    - name: Copy k8s repo
      copy:
        src: k8s.repo
        dest: /etc/yum.repos.d/k8s.repo
    - name: Install k8s components
      shell: |
        dnf makecache
        dnf install -y {kubelet,kubeadm,kubectl} --disableexcludes=kubernetes
        systemctl enable --now kubelet.service
        systemctl status kubelet --no-pager
        sudo dnf -y install iproute-tc
        sudo dnf install yum-plugin-versionlock -y
        sudo dnf versionlock kubelet kubeadm kubectl
        mkdir /opt/bin
        curl -fsSLo /opt/bin/flanneld https://github.com/flannel-io/flannel/releases/download/v0.20.1/flannel-v0.20.1-linux-amd64.tar.gz
        chmod +x /opt/bin/flanneld
    - name: Install nfs client
      shell: |
        sudo dnf install nfs-utils nfs4-acl-tools -y
        sudo systemctl start nfs-client.target
        sudo systemctl enable nfs-client.target
        sudo systemctl status nfs-client.target --no-pager