---
- name: Install OS utils
  hosts: all
  become: true
  remote_user: rocky
  #gather_facts: false
  tasks:
    - name: install epel-release
      dnf:
        name: epel-release
        state: present
    - name: install htop
      package:
        name: htop
        state: present
    - name: install nmap
      package:
        name: nmap
        state: present
    - name: install dnsutils
      package:
        name: dnsutils
        state: present
