---
- name: Enable etcd firewall
  hosts: all
  become: true
  remote_user: rocky
  tasks:
    - name: Install FirewallD
      shell: |
        sudo dnf install firewalld -y
        sudo systemctl enable firewalld
        sudo systemctl start firewalld
        sudo firewall-cmd --permanent --add-port=2379/tcp --zone=public
        sudo firewall-cmd --permanent --add-port=2380/tcp --zone=public
        sudo firewall-cmd --permanent --add-port=22/tcp --zone=public
        sudo firewall-cmd --permanent --add-port=6556/tcp --zone=public
        sudo firewall-cmd --permanent --add-port=9200/tcp --zone=public
        sudo systemctl restart firewalld